Set cover reduction method
prime-slam/place-recognition-db pull request #7
Opened 2022-11-04 18:18 UTC by vnmsklnk

This PR contains an implementation of a database reduction method based on a set cover problem

2022-11-06 13:40 UTC, anastasiia-kornilova requested changes

2022-11-06 13:40 UTC, anastasiia-kornilova commented on src/reduction_methods/set_cover.py
> +    def __init__(self, db_size: Optional[int] = None, voxel_size: float = 0.1):
db_size should be renamed, not clear what `size` means, it could be memory not amount of frames

2022-11-06 13:40 UTC, anastasiia-kornilova commented on src/reduction_methods/set_cover.py
> +        if self.db_size is None:
One trinary operators could be here

2022-11-06 13:40 UTC, anastasiia-kornilova commented on src/reduction_methods/set_cover.py
> +            chosen_frame = np.argmax(np.sum(coverage_mat, axis=1))
chosen_frame_index is better

2022-11-06 13:40 UTC, anastasiia-kornilova commented on src/reduction_methods/set_cover.py
> +    """The method reduces database by set cover greedy algorithm"""
Please, explain shortly how algorithm works

2022-11-07 16:50 UTC, anastasiia-kornilova requested changes

2022-11-07 16:50 UTC, anastasiia-kornilova commented on src/reduction_methods/set_cover.py
> +    coverage_mat = dok_array((len(frames_voxels), len(voxels_enum)), dtype=np.uint8)
Why do we use uints if we have binary matrix?

2022-11-07 16:50 UTC, anastasiia-kornilova commented on src/reduction_methods/set_cover.py
> +            mask = mask[mask]
Let's rename for what exactly this mask stands. I suppose that is `not_covered_voxels_mask`? Well, maybe shorter name, but should be renamed

2022-11-07 17:47 UTC, anastasiia-kornilova approved these changes

2022-11-08 06:21 UTC, DmiitriyJarosh approved these changes

2022-11-08 09:44 UTC, merged